import Foundation

/// Robust resource bundle resolver.
///
/// `Bundle.module`, generated by SwiftPM, is unsuitable for the manually
/// packaged `.app`: it resolves `Bundle.main.bundleURL` (the `.app` root,
/// e.g. `/Applications/Sesame.app`) rather than `Contents/Resources` where the
/// packaging script places the resource bundle, and its only fallback is an
/// absolute compile-time build path that does not exist on the user's machine.
/// When both miss, `Bundle.module` calls `fatalError`, crashing at launch.
///
/// This resolver instead probes every plausible location and degrades to `nil`
/// so callers can handle a missing resource gracefully instead of crashing.
private final class ResourceBundleToken {}

extension Bundle {
    /// The `Sesame_Sesame.bundle` resource bundle, or `nil` if it cannot be
    /// located. Resolved once and cached.
    static let appResources: Bundle? = {
        let bundleName = "Sesame_Sesame.bundle"

        let candidateBases: [URL] = [
            // Packaged `.app`: Contents/Resources/Sesame_Sesame.bundle
            Bundle.main.resourceURL,
            // Bare executable / `swift run`: bundle sits next to the binary.
            Bundle.main.bundleURL,
            Bundle(for: ResourceBundleToken.self).resourceURL,
            Bundle(for: ResourceBundleToken.self).bundleURL,
        ].compactMap { $0 }

        for base in candidateBases {
            let url = base.appendingPathComponent(bundleName)
            if let bundle = Bundle(url: url) {
                return bundle
            }
        }

        return nil
    }()
}
